services:
  website:
    image: ghcr.io/ionaru/rangers-mono/website:${RANGERS_BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: deploy/nuxt.Dockerfile
    ports:
      - "3001:3000"
    environment:
      - AUTH_ORIGIN
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - AUTH_SESSION_SECRET
    restart: unless-stopped
    healthcheck:
      test: 'wget --header="Accept: text/html" localhost:3001/graphql -q --spider'
      start_period: 30s
