services:
  website:
    image: ghcr.io/ionaru/rangers-mono/website:${RANGERS_BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: deploy/nuxt.Dockerfile
      args:
        - AUTH_ORIGIN
    ports:
      - "3001:3000"
    environment:
      - NEXTAUTH_URL
      - AUTH_ORIGIN
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - AUTH_SESSION_SECRET
    restart: unless-stopped
    healthcheck:
      test: 'Invoke-WebRequest -Uri http://localhost:3001 -Headers @{"Accept"="text/html"} -UseBasicParsing > $null'
      start_period: 30s
